[[language]]
name = "clingo"
scope = "scope.clingo"
file-types = ["lp"]
comment-token = "%"
roots = []
indent = { tab-width = 2, unit = "  "}
language-server = { command = "asp-language-server", args = ["--stdio"]}

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
language-server = { command = "rust-analyzer" }
indent = { tab-width = 4, unit = "    " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "python"
language-server = { command = "pylsp" }
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[language.config.pylsp.plugins]
pyflakes = { enabled = false }
mccabe = { enabled = false }
pyls_isort = { enabled = false }
pycodestyle = { enabled = false, maxLineLength = 79 }
pydocstyle = { enabled = false }
autopep8 = { enabled = false }
yapf = { enabled = false }
flake8 = { enabled = false }
pylint = { enabled = false }
ruff = { enabled = true, extendSelect = ["I"] }
mypy = { enabled = true, live_mode = true, strict = true }

[[language]]
name = "latex"

[language.config.texlab.build]
onSave = true
forwardSearchAfter = true

[language.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:1:%f", "%p" ]

[language.config.texlab.chktex]
onEdit = true